<?php
namespace Database\Seeders;

use App\Models\Kelas;
use App\Models\Siswa;
use App\Models\TahunAjaran;
use Illuminate\Database\Seeder;

class ImportSiswaMbgSeeder extends Seeder
{
    public function run(): void
    {
        $tahunAjaran = TahunAjaran::aktifSaatIni();

        // Pastikan kelas 1-6 tersedia (dibuat otomatis kalau belum ada)
        $kelasPerTingkat = [];
        for ($t = 1; $t <= 6; $t++) {
            $kelasPerTingkat[$t] = Kelas::firstOrCreate(
                ['nama_kelas' => (string) $t],
                ['tingkat' => $t, 'tahun_ajaran_id' => $tahunAjaran?->id]
            );
        }

        $data = [
            ['nisn'=>'3188838988','nama'=>'AFIQA MEDINA AZALEA','jenis_kelamin'=>'P','tempat_lahir'=>'PERBAUNGAN','tanggal_lahir'=>'2019-04-20','nama_ortu'=>'SUWANDI','tingkat'=>1],
            ['nisn'=>'3184997584','nama'=>'AL AMIN RAFLY ABQHORY','jenis_kelamin'=>'L','tempat_lahir'=>'CIBUBUR','tanggal_lahir'=>'2018-12-09','nama_ortu'=>'MUHAMMAD MA\'RUF','tingkat'=>1],
            ['nisn'=>'3191702265','nama'=>'AL HAFIDS MARK','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2019-05-23','nama_ortu'=>'EDI MARK','tingkat'=>1],
            ['nisn'=>'3197439727','nama'=>'ALFI SYAHRI AR-RAHMAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2019-05-20','nama_ortu'=>'AHMAT HARIANTO','tingkat'=>1],
            ['nisn'=>'3174138074','nama'=>'AWALUL FITRA','jenis_kelamin'=>'L','tempat_lahir'=>'LANGSA','tanggal_lahir'=>'2017-06-26','nama_ortu'=>'SRI MULIYANA','tingkat'=>1],
            ['nisn'=>'3180222872','nama'=>'BADRUZZAMAN','jenis_kelamin'=>'L','tempat_lahir'=>'SIGLI','tanggal_lahir'=>'2018-12-05','nama_ortu'=>'MALEK BUDIMAN','tingkat'=>1],
            ['nisn'=>'3171639763','nama'=>'CLAUDYA PUTRI NAVISAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-06-19','nama_ortu'=>'JEFRI RONAL JOHANES','tingkat'=>1],
            ['nisn'=>'3193934085','nama'=>'FATIR NUALI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2019-03-04','nama_ortu'=>'INDRA NUR ALI','tingkat'=>1],
            ['nisn'=>'3198938945','nama'=>'HILYA ANNASYAH LESMANA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2019-02-21','nama_ortu'=>'DIVA FRANSKANSYAH LESMANA','tingkat'=>1],
            ['nisn'=>'3180195428','nama'=>'MHD ALIF MAGHRIZA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-01-16','nama_ortu'=>'PRAYOGO','tingkat'=>1],
            ['nisn'=>'3181622926','nama'=>'MUHAMMAD ADDLI ALFARIZI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-10-19','nama_ortu'=>'ABADI','tingkat'=>1],
            ['nisn'=>'3185376381','nama'=>'OZIL EL SHARAWY SIREGAR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-12-25','nama_ortu'=>'SAMSINAR HARAHAP','tingkat'=>1],
            ['nisn'=>'3185329118','nama'=>'RAKA PRAYOGA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-07-05','nama_ortu'=>'SULAIMAN','tingkat'=>1],
            ['nisn'=>'3194447631','nama'=>'SAHIRA BR GINTING','jenis_kelamin'=>'P','tempat_lahir'=>'POHAN JULU','tanggal_lahir'=>'2019-08-01','nama_ortu'=>'YOHANNA SIAHAAN','tingkat'=>1],
            ['nisn'=>'3197205989','nama'=>'SHABBIAH KHANZA ALESHA','jenis_kelamin'=>'P','tempat_lahir'=>'DELI SERDANG','tanggal_lahir'=>'2019-07-04','nama_ortu'=>'ZAENAL ARIFIN','tingkat'=>1],
            ['nisn'=>'3183299183','nama'=>'YUDHA ANDIKA PRATAMA','jenis_kelamin'=>'L','tempat_lahir'=>'ACEH UTARA','tanggal_lahir'=>'2018-09-18','nama_ortu'=>'PARYONO','tingkat'=>1],
            ['nisn'=>'3194655927','nama'=>'ZAHEER HABIBULLAH KHAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2019-08-02','nama_ortu'=>'AHMED NAWAZ','tingkat'=>1],
            ['nisn'=>'3181358425','nama'=>'ZAKIRA KHUMAIROH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-09-18','nama_ortu'=>'MUHAMMAD MARJUKI','tingkat'=>1],
            ['nisn'=>'3162508800','nama'=>'ADNAN ABDULLAH','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-12-31','nama_ortu'=>'ASRIL','tingkat'=>2],
            ['nisn'=>'3174677889','nama'=>'AISYAH AQILLA NAZWA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-10-17','nama_ortu'=>'MUHAMMAD RIDWAN','tingkat'=>2],
            ['nisn'=>'3171083405','nama'=>'AKBAR MAULANA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-08-17','nama_ortu'=>'SURYADI','tingkat'=>2],
            ['nisn'=>'3171182676','nama'=>'ARBAA HATAYA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-08-28','nama_ortu'=>'EKO SAPUTRO','tingkat'=>2],
            ['nisn'=>'3185906144','nama'=>'ARKHAN RAMADHAN BAHRI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-05-20','nama_ortu'=>'SAMSUL BAHRI','tingkat'=>2],
            ['nisn'=>null,'nama'=>'ASIVA AULIA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-02-20','nama_ortu'=>'MUHAMMAD CHAIRUN','tingkat'=>2],
            ['nisn'=>'3174349718','nama'=>'AYRA NAFEEZA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-06-20','nama_ortu'=>'SURANTO','tingkat'=>2],
            ['nisn'=>'3150922932','nama'=>'AZKA FAUZAN RIDWAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-09-01','nama_ortu'=>'MUHAMMAD RIDWAN','tingkat'=>2],
            ['nisn'=>'3171948373','nama'=>'CHELSEA ARSYILASIREGAR','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-12-11','nama_ortu'=>'SAMSINAR HARAHAP','tingkat'=>2],
            ['nisn'=>'3182269211','nama'=>'DEA GEULIS NURJANNAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-05-16','nama_ortu'=>'ADE SATRIA','tingkat'=>2],
            ['nisn'=>'3180543329','nama'=>'FAHRIL RAMADHAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-05-24','nama_ortu'=>'SIFYAN ABDI','tingkat'=>2],
            ['nisn'=>'3183762959','nama'=>'FATIH ALFAREZQY SUBIANTORO','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-05-12','nama_ortu'=>'TRI SUBIANTORO','tingkat'=>2],
            ['nisn'=>'3174573034','nama'=>'FIRZA FAHREZA ASWAN','jenis_kelamin'=>'L','tempat_lahir'=>'PERBAUNGAN','tanggal_lahir'=>'2017-09-04','nama_ortu'=>'FANI ASWAN','tingkat'=>2],
            ['nisn'=>'3170906084','nama'=>'INTAN PUTRI ZAHIRA SIREGAR','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-11-15','nama_ortu'=>'ADI SOFYAN SIREGAR','tingkat'=>2],
            ['nisn'=>'3175042711','nama'=>'KHADIJAH AGUSTA HARTONO','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-08-28','nama_ortu'=>'Ir. ARDHI HARTONO','tingkat'=>2],
            ['nisn'=>'3170339339','nama'=>'KIRANA DEWI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-08-07','nama_ortu'=>'ALFIAN','tingkat'=>2],
            ['nisn'=>'3185849610','nama'=>'LUQMAN PRATAMA WIBOWO','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-03-21','nama_ortu'=>'WIBOWO','tingkat'=>2],
            ['nisn'=>'3152133311','nama'=>'MUHAMAD IKSAN','jenis_kelamin'=>'L','tempat_lahir'=>'BOGOR','tanggal_lahir'=>'2015-08-19','nama_ortu'=>'ASIK ASIANG','tingkat'=>2],
            ['nisn'=>'3173439166','nama'=>'MUHAMMAD AL FAEYZA BUHQORI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-12-06','nama_ortu'=>'BAMBANG ERIANTO','tingkat'=>2],
            ['nisn'=>null,'nama'=>'NOVITA QHAIRATUL AZAHRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-11-13','nama_ortu'=>'HENDRA MUSTIKA','tingkat'=>2],
            ['nisn'=>null,'nama'=>'RAFIF KHANZA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-04-13','nama_ortu'=>'AGUS FAZAR','tingkat'=>2],
            ['nisn'=>'3178874899','nama'=>'RINALDY','jenis_kelamin'=>'L','tempat_lahir'=>'BUKIT KESUMA','tanggal_lahir'=>'2017-10-04','nama_ortu'=>'SAUDI','tingkat'=>2],
            ['nisn'=>'3188323780','nama'=>'SADDAM HUSAIN SIREGAR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-01-18','nama_ortu'=>'MUHAMMAD NIZAR SIREGAR','tingkat'=>2],
            ['nisn'=>'3187670192','nama'=>'SYAHILA DOPAN SARASSANI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-01-14','nama_ortu'=>'DOPAN OZI RAMADHAN','tingkat'=>2],
            ['nisn'=>'3182157256','nama'=>'TALITHA RUQQAYA AZIZAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2018-05-27','nama_ortu'=>'RACHMAT HIDAYAT','tingkat'=>2],
            ['nisn'=>'3179146655','nama'=>'TAQIYYAH ZIANNISA NURRAHMAN','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-12-24','nama_ortu'=>'DADANG RAMADHAN','tingkat'=>2],
            ['nisn'=>'3173763179','nama'=>'TIARA ALZAHSY','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-07-02','nama_ortu'=>'JULIANTO','tingkat'=>2],
            ['nisn'=>'3171924336','nama'=>'WIRA BUHARI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-04-04','nama_ortu'=>'WAHYUDI','tingkat'=>2],
            ['nisn'=>'3179672060','nama'=>'ADITY DWI AYUNDA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-01-20','nama_ortu'=>'SUDARMA','tingkat'=>3],
            ['nisn'=>'3164003958','nama'=>'ADITYA NAUFAL AZKA SEMBIRING','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-02-11','nama_ortu'=>'M ZAID BUDI SEMBIRING','tingkat'=>3],
            ['nisn'=>'3165342451','nama'=>'AHMAD ZAKI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-08-07','nama_ortu'=>'NUR MUHAMMAD','tingkat'=>3],
            ['nisn'=>'3171603092','nama'=>'AL BANI KHOIR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-07-11','nama_ortu'=>'BUDI S','tingkat'=>3],
            ['nisn'=>'3169395543','nama'=>'AL ZHEA MISHALL NAVISHA','jenis_kelamin'=>'P','tempat_lahir'=>'DELI SERDANG','tanggal_lahir'=>'2016-09-20','nama_ortu'=>'DEDY SYAHPUTRA K','tingkat'=>3],
            ['nisn'=>'3163965140','nama'=>'ALI ARKHA ADYTIA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-10-28','nama_ortu'=>'USMAN ADITYA','tingkat'=>3],
            ['nisn'=>'3164673956','nama'=>'ALYA REZQILLAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-09-13','nama_ortu'=>'PUTRA ANANDA','tingkat'=>3],
            ['nisn'=>'3174759401','nama'=>'AYUMNA HALIMATUL SYA\'DIYAH','jenis_kelamin'=>'P','tempat_lahir'=>'CILACAP','tanggal_lahir'=>'2017-03-12','nama_ortu'=>'IRCHAM','tingkat'=>3],
            ['nisn'=>null,'nama'=>'BINTANG ASMARA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-05-07','nama_ortu'=>'ANGGA ASMARA','tingkat'=>3],
            ['nisn'=>'3135645636','nama'=>'CHANDRA DWI ADITYA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-05-07','nama_ortu'=>'IRWAN SUSANTRI','tingkat'=>3],
            ['nisn'=>'3169532882','nama'=>'FARHAN SYAHPUTRA NURALI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-06-04','nama_ortu'=>'INDRA NUR ALI','tingkat'=>3],
            ['nisn'=>'3173391905','nama'=>'HAFIS DZIKRI POTU','jenis_kelamin'=>'L','tempat_lahir'=>'TANJUNG MORAWA','tanggal_lahir'=>'2017-02-14','nama_ortu'=>'RINALDI FOTU','tingkat'=>3],
            ['nisn'=>'3168366332','nama'=>'ISMAIL SAPUTRA SIREGAR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-09-15','nama_ortu'=>'EDI SAPUTRA','tingkat'=>3],
            ['nisn'=>'3176535316','nama'=>'MHD ARKHAN RAFEYZA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-01-31','nama_ortu'=>'M FIKRI AGUSTIAN','tingkat'=>3],
            ['nisn'=>'3177744772','nama'=>'MUHAMMAD ERDOGAN SYAHMI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-05-05','nama_ortu'=>'DICKY DZULFAHMI','tingkat'=>3],
            ['nisn'=>'3176351650','nama'=>'MUHAMMAD RAMADANI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-06-09','nama_ortu'=>'ERWAN','tingkat'=>3],
            ['nisn'=>'3170378969','nama'=>'MUHAMMAD ALFA RIZKY','jenis_kelamin'=>'L','tempat_lahir'=>'LANGKAT','tanggal_lahir'=>'2017-04-24','nama_ortu'=>'SHERLY RAMADHANI BR SITEPU','tingkat'=>3],
            ['nisn'=>'3176238528','nama'=>'MUHAMMAD RYAN ARRAHMAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-05-07','nama_ortu'=>'AHMAT HARIANTO','tingkat'=>3],
            ['nisn'=>'3179855581','nama'=>'NAURA MEDINA SYABIL','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-05-16','nama_ortu'=>'SUGIANTO','tingkat'=>3],
            ['nisn'=>'3169636427','nama'=>'NAYRA KHALIFA NOVIN','jenis_kelamin'=>'P','tempat_lahir'=>'SUNGGAL','tanggal_lahir'=>'2016-12-11','nama_ortu'=>'NOPIN','tingkat'=>3],
            ['nisn'=>'3158955940','nama'=>'NOVIKA NAZWA AZAHRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-11-11','nama_ortu'=>'SUPARNO','tingkat'=>3],
            ['nisn'=>'3163802361','nama'=>'PUTRI SYAQILA','jenis_kelamin'=>'P','tempat_lahir'=>'LANGKAT','tanggal_lahir'=>'2016-11-13','nama_ortu'=>'MUHAMMAD KHALIL, S.PD I','tingkat'=>3],
            ['nisn'=>'3162986515','nama'=>'RIFQI AHMAD AL FATTAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-06-08','nama_ortu'=>'FAHRUNNISA','tingkat'=>4],
            ['nisn'=>'3162649065','nama'=>'RIFQY RAMADHANSYAH','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-06-30','nama_ortu'=>'BRIAN LIANSYAH','tingkat'=>3],
            ['nisn'=>'3162948307','nama'=>'SYAHDAM AL KARIM','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-12-02','nama_ortu'=>'RESMANTO','tingkat'=>3],
            ['nisn'=>'3141422759','nama'=>'SYAHDANA HAIKAL','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-11-23','nama_ortu'=>'RESMANTO','tingkat'=>3],
            ['nisn'=>'3163717156','nama'=>'TRI WANDA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-06-02','nama_ortu'=>'IRWANSYAH PUTRA','tingkat'=>3],
            ['nisn'=>'3163552170','nama'=>'UMAR NOOR HABIB','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-09-26','nama_ortu'=>'HERU DARMA','tingkat'=>3],
            ['nisn'=>'3173447405','nama'=>'VIVIYAN ZAHRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2017-02-25','nama_ortu'=>'SUWADI','tingkat'=>3],
            ['nisn'=>'3144050665','nama'=>'ADITYA ZAIN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-12-25','nama_ortu'=>'AWALUDIN','tingkat'=>4],
            ['nisn'=>'3169343517','nama'=>'AIDIL FURQON MANURUNG','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-01-05','nama_ortu'=>'ANDRE GIOVANI MANURUNG','tingkat'=>4],
            ['nisn'=>'3161257461','nama'=>'AISYAH SYIFA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-09-19','nama_ortu'=>'LINDA','tingkat'=>4],
            ['nisn'=>'3153402260','nama'=>'ALIKA KANAYA SAHILA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-08-26','nama_ortu'=>'DENI IARAWAN','tingkat'=>4],
            ['nisn'=>'3167383976','nama'=>'ALISAH PUTRI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-02-26','nama_ortu'=>'MUHAMMAD MARJUKI','tingkat'=>4],
            ['nisn'=>'3156363455','nama'=>'ALVIN HADI PUTRA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-08-31','nama_ortu'=>'MAHDI','tingkat'=>4],
            ['nisn'=>'3165522299','nama'=>'ANINDHITA RISMANA PUTRI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-06-01','nama_ortu'=>'SUARISMAN','tingkat'=>4],
            ['nisn'=>'3144951910','nama'=>'AQILA AULYA UMMAIRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-01-02','nama_ortu'=>'IBARHIM','tingkat'=>4],
            ['nisn'=>'3163073780','nama'=>'ARSYLA ZAHRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2016-02-17','nama_ortu'=>'PRAYOGO','tingkat'=>4],
            ['nisn'=>'3144136034','nama'=>'ATAYA RAFIQ DAMANIK','jenis_kelamin'=>'L','tempat_lahir'=>'PEMATANGSIANTAR','tanggal_lahir'=>'2014-09-19','nama_ortu'=>'AYYUB ARDIANSYAH DAMANIK','tingkat'=>4],
            ['nisn'=>'3159257814','nama'=>'DAFFA MIKAIL GUMILAR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-04-22','nama_ortu'=>'FREIDY WAHYU GUMILAR','tingkat'=>4],
            ['nisn'=>'3135581824','nama'=>'DAFFA NAUFAL ASKA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-12-10','nama_ortu'=>'M ISHAK','tingkat'=>4],
            ['nisn'=>'3158468790','nama'=>'FAUZI GINTING','jenis_kelamin'=>'L','tempat_lahir'=>'Medan','tanggal_lahir'=>'2015-02-17','nama_ortu'=>'MURSYIDAH','tingkat'=>4],
            ['nisn'=>'3152482926','nama'=>'GHIBRAN AL FAWWAZ HUTAPEA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-10-06','nama_ortu'=>'KHAIRUL SAKBAN HUTAPEA','tingkat'=>4],
            ['nisn'=>'3129939505','nama'=>'ILHAM KAIRON','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2012-06-22','nama_ortu'=>'WIWIN DARMAWAN','tingkat'=>4],
            ['nisn'=>'3161479056','nama'=>'Muhammad Syuhada','jenis_kelamin'=>'L','tempat_lahir'=>'Medan','tanggal_lahir'=>'2016-05-21','nama_ortu'=>'yaman','tingkat'=>4],
            ['nisn'=>'3150140376','nama'=>'NAZLA CITRA ALPRIANI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-12-31','nama_ortu'=>'SUPRIADI','tingkat'=>4],
            ['nisn'=>'3145587042','nama'=>'SAKINAH AMANDA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-10-13','nama_ortu'=>'WIWIN DARMAWAN','tingkat'=>4],
            ['nisn'=>'3156695067','nama'=>'SETIABUDI MUHAMMAD HARTONO','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-03-18','nama_ortu'=>'IR ADHI HARTONO','tingkat'=>4],
            ['nisn'=>'3152514871','nama'=>'SHHEINA NANDITA PUTRI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-02-03','nama_ortu'=>'SYARIFAH NUR ALI','tingkat'=>4],
            ['nisn'=>'3146402696','nama'=>'SITI HAJAR','jenis_kelamin'=>'P','tempat_lahir'=>'LANGKAT','tanggal_lahir'=>'2014-06-16','nama_ortu'=>'MUHAMMAD KALIL, S.PD I','tingkat'=>4],
            ['nisn'=>'3153856550','nama'=>'SYAHWA NUR ZAHIRA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-07-29','nama_ortu'=>'ZAENAL ARIFIN','tingkat'=>4],
            ['nisn'=>'3144087788','nama'=>'ALDI PURANDY','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-10-22','nama_ortu'=>'ALI SAHBANA','tingkat'=>5],
            ['nisn'=>'3132616668','nama'=>'ALISYA ALVIANA','jenis_kelamin'=>'P','tempat_lahir'=>'LANGKAT','tanggal_lahir'=>'2013-10-27','nama_ortu'=>'SUYANTO','tingkat'=>5],
            ['nisn'=>'147293313','nama'=>'AQMAL SANTO PRATAMA SIREGAR','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-10-14','nama_ortu'=>'MUHAMMAD NIZAR SIREGAR','tingkat'=>5],
            ['nisn'=>'3153650913','nama'=>'ARFA HABIBI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-05-23','nama_ortu'=>'BAMBANG','tingkat'=>5],
            ['nisn'=>'3159407372','nama'=>'ARKAAIMANA PUTRA AL MKAIL','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-01-10','nama_ortu'=>'PUTRA ABDI WIBOWO','tingkat'=>5],
            ['nisn'=>'3141388103','nama'=>'ASILA KINANTI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-06-09','nama_ortu'=>'BAMBANG','tingkat'=>5],
            ['nisn'=>'3148146946','nama'=>'ASILLA SALSABILLAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-02-13','nama_ortu'=>'RUDY','tingkat'=>5],
            ['nisn'=>'3140114411','nama'=>'BALQIS FITRIA NURRAHMAN','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-08-07','nama_ortu'=>'DADANG RAMADHAN','tingkat'=>5],
            ['nisn'=>'3140734266','nama'=>'callisca carolin','jenis_kelamin'=>'P','tempat_lahir'=>'medan','tanggal_lahir'=>'2014-01-23','nama_ortu'=>'Jefri Ronal Johanes','tingkat'=>5],
            ['nisn'=>'3150746837','nama'=>'Devin callistino','jenis_kelamin'=>'L','tempat_lahir'=>'medan','tanggal_lahir'=>'2015-03-21','nama_ortu'=>'Jefri Ronal Johanes','tingkat'=>5],
            ['nisn'=>'3131937522','nama'=>'JASMINE AULIA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-01-25','nama_ortu'=>'ALAMSYAH','tingkat'=>5],
            ['nisn'=>'3147534151','nama'=>'LESTARI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-06-17','nama_ortu'=>'SUDARMAJI','tingkat'=>5],
            ['nisn'=>'3143890449','nama'=>'M ALDO SYAHRIZAL','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-08-05','nama_ortu'=>'ANTONI RIZAL','tingkat'=>5],
            ['nisn'=>'3147304025','nama'=>'M AMRI PAL','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-08-28','nama_ortu'=>'M RAPI','tingkat'=>5],
            ['nisn'=>'3155162727','nama'=>'m ilham','jenis_kelamin'=>'L','tempat_lahir'=>'medan','tanggal_lahir'=>'2015-05-04','nama_ortu'=>'arida','tingkat'=>5],
            ['nisn'=>'3147563207','nama'=>'M IQBAL ALPRIANDHI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-05-29','nama_ortu'=>'SUPRIADI','tingkat'=>5],
            ['nisn'=>'3142999642','nama'=>'mora arsyil adtrada nasution','jenis_kelamin'=>'L','tempat_lahir'=>'rantauprapat','tanggal_lahir'=>'2014-03-06','nama_ortu'=>'khairuddin nasution','tingkat'=>5],
            ['nisn'=>'116402706','nama'=>'MUHAMMAD FADIEL MULYO','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2011-04-05','nama_ortu'=>'SUGENG WIJAYA','tingkat'=>5],
            ['nisn'=>'3149110104','nama'=>'NABILA AYU LESTARI','jenis_kelamin'=>'P','tempat_lahir'=>'LANGKAT','tanggal_lahir'=>'2014-10-17','nama_ortu'=>'ERWAN','tingkat'=>5],
            ['nisn'=>'3150540729','nama'=>'NADIRA AZ ZAHRA','jenis_kelamin'=>'P','tempat_lahir'=>'LHOKSEUMAWE','tanggal_lahir'=>'2015-06-02','nama_ortu'=>'FEDIANSYAH','tingkat'=>5],
            ['nisn'=>'3154890966','nama'=>'PRAHARYA ADI TAMA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-02-15','nama_ortu'=>'ANDHY SATRIA UTAMA','tingkat'=>5],
            ['nisn'=>'3148529773','nama'=>'RAFA ALIANDO CAISAR TAMPUBOLON','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-08-27','nama_ortu'=>'RAHMAD ROMY A TAMPUBOLON','tingkat'=>5],
            ['nisn'=>'133194469','nama'=>'RAISYA DANIATI','jenis_kelamin'=>'P','tempat_lahir'=>'SIGLI','tanggal_lahir'=>'2013-12-24','nama_ortu'=>'MALEK BUDIMAN','tingkat'=>5],
            ['nisn'=>'3143744945','nama'=>'REVAN ALFRIZA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-10-16','nama_ortu'=>'AGUS FAZAR','tingkat'=>5],
            ['nisn'=>'3143106983','nama'=>'SYAHIRAH NADHIFAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-09-19','nama_ortu'=>'SUHENDRI','tingkat'=>5],
            ['nisn'=>'3158266963','nama'=>'UCI PERMATA SARI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2015-06-25','nama_ortu'=>'ILHAMBRI','tingkat'=>5],
            ['nisn'=>'3137619416','nama'=>'ZASKYAH','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-01-31','nama_ortu'=>'INDRA JAYA','tingkat'=>5],
            ['nisn'=>'3141770951','nama'=>'ABE AL HABSI','jenis_kelamin'=>'L','tempat_lahir'=>'DUMAI','tanggal_lahir'=>'2014-01-11','nama_ortu'=>'IRWANSYAH','tingkat'=>6],
            ['nisn'=>'3144378951','nama'=>'ABIMANA PUTRA EL AZZURRI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-01-09','nama_ortu'=>'PUTRA ABDI WIBOWO','tingkat'=>6],
            ['nisn'=>'3143340061','nama'=>'ADITYA PRATAMA ARIFIN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-03-27','nama_ortu'=>'SUDARMA','tingkat'=>6],
            ['nisn'=>'133646858','nama'=>'Adzka Attaya Zidni','jenis_kelamin'=>'L','tempat_lahir'=>'Medan','tanggal_lahir'=>'2013-06-30','nama_ortu'=>'Swandi','tingkat'=>6],
            ['nisn'=>'3142938203','nama'=>'AIRA RAMADHANI BR HASUGIAN','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-07-14','nama_ortu'=>'SARIPUDDIN HASUGIAN','tingkat'=>6],
            ['nisn'=>'3133653101','nama'=>'ANAQU VARDANO ARMADHAN P','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-08-02','nama_ortu'=>'AHMAD NAHARDI PARDEDE','tingkat'=>6],
            ['nisn'=>'3143464192','nama'=>'ASYIFAH VIRGINIA SUGARA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-03-06','nama_ortu'=>'OGI RANDRA SUGARA','tingkat'=>6],
            ['nisn'=>'3149656248','nama'=>'ATHALLAH ARKHAN HARAHAP','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-01-20','nama_ortu'=>'KHAIRUL AMRI HARAHAP','tingkat'=>6],
            ['nisn'=>'3137991844','nama'=>'AURA FANSHA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-02-21','nama_ortu'=>'MIRSAL AFFANDI','tingkat'=>6],
            ['nisn'=>'3134801070','nama'=>'AZQHIA AZHARI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-11-26','nama_ortu'=>'KUSMIADI','tingkat'=>6],
            ['nisn'=>'3130425761','nama'=>'BARRY FARHANSYAH','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-12-31','nama_ortu'=>'JUNAERI','tingkat'=>6],
            ['nisn'=>'3145222840','nama'=>'CARISA PUTRI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-03-18','nama_ortu'=>'JULIANTO','tingkat'=>6],
            ['nisn'=>'3134868628','nama'=>'DESGI MIRZACKY','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-12-03','nama_ortu'=>'SUJARWAN','tingkat'=>6],
            ['nisn'=>'3139156259','nama'=>'DWI SEPTI AULIA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-09-18','nama_ortu'=>'M ALI','tingkat'=>6],
            ['nisn'=>'3141717374','nama'=>'FAIZAL AHMAD SETIAWAN','jenis_kelamin'=>'L','tempat_lahir'=>'KENDAL','tanggal_lahir'=>'2014-05-20','nama_ortu'=>'A TAUHID','tingkat'=>6],
            ['nisn'=>'3149315951','nama'=>'KHANZA UMAIRAH BILQIS','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-02-20','nama_ortu'=>'MUHAMMAD RIDWAN','tingkat'=>6],
            ['nisn'=>'3144851120','nama'=>'MHD AFRIANSYAH','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-04-09','nama_ortu'=>'MUHAMMAD ALI','tingkat'=>6],
            ['nisn'=>'3144787633','nama'=>'MHD VIRZA ZIKRI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-02-28','nama_ortu'=>'PRAYOGO','tingkat'=>6],
            ['nisn'=>'3139317707','nama'=>'MUHAMMAD ADRIAN ARDZAKI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-03-17','nama_ortu'=>'ABDULLAH','tingkat'=>6],
            ['nisn'=>'3133959846','nama'=>'MUHAMMAD ADRIAN ARDZIKI','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-03-17','nama_ortu'=>'ABDULLAH','tingkat'=>6],
            ['nisn'=>'147002433','nama'=>'MUHAMMAD AL FASHA','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-04-04','nama_ortu'=>'BUDI S','tingkat'=>6],
            ['nisn'=>'3131483433','nama'=>'MUHAMMAD ALDIANSYAH','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-11-18','nama_ortu'=>'MUHAMMAD MARZUKI','tingkat'=>6],
            ['nisn'=>'3139217862','nama'=>'MUHAMMAD ALIF NUR','jenis_kelamin'=>'L','tempat_lahir'=>'LANGSA','tanggal_lahir'=>'2013-09-12','nama_ortu'=>'SYAMSUDDIN','tingkat'=>6],
            ['nisn'=>'3124895029','nama'=>'MUHAMMAD ANTAFIN','jenis_kelamin'=>'L','tempat_lahir'=>'NUMBING','tanggal_lahir'=>'2012-09-08','nama_ortu'=>'JOKO SAKTI','tingkat'=>6],
            ['nisn'=>'3142762243','nama'=>'NINDIA AYU PRAMUSITA','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2014-07-02','nama_ortu'=>'BAYU PRATAMA','tingkat'=>6],
            ['nisn'=>'3146497693','nama'=>'RAHMAD MULYADI SIREGAR','jenis_kelamin'=>'L','tempat_lahir'=>'KOTA PADANGSIDIMPUAN','tanggal_lahir'=>'2014-06-14','nama_ortu'=>'EDI SYAHPUTRA SRG','tingkat'=>6],
            ['nisn'=>'146732198','nama'=>'RAZIQ HANAN','jenis_kelamin'=>'L','tempat_lahir'=>'Pariaman','tanggal_lahir'=>'2014-05-24','nama_ortu'=>'MUHAMMAD MA\'RUF','tingkat'=>6],
            ['nisn'=>'3134197836','nama'=>'RENDI KURNIAWAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-11-17','nama_ortu'=>'DRIYANTO','tingkat'=>6],
            ['nisn'=>'3139062771','nama'=>'SALSABILA RAMADHANI','jenis_kelamin'=>'P','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-07-30','nama_ortu'=>'ALFIAN','tingkat'=>6],
            ['nisn'=>'3137996949','nama'=>'SYAUQI IHSAN','jenis_kelamin'=>'L','tempat_lahir'=>'MEDAN','tanggal_lahir'=>'2013-12-05','nama_ortu'=>'JUNAIDI','tingkat'=>6],
        ];

        foreach ($data as $d) {
            // Siswa tanpa NISN di data sumber dicocokkan lewat nama + tanggal lahir,
            // supaya tidak tertukar/bertabrakan satu sama lain saat seeder dijalankan ulang.
            $kunci = $d['nisn']
                ? ['nisn' => $d['nisn']]
                : ['nama' => $d['nama'], 'tanggal_lahir' => $d['tanggal_lahir']];

            Siswa::updateOrCreate(
                $kunci,
                [
                    'nisn' => $d['nisn'],
                    'nama' => $d['nama'],
                    'jenis_kelamin' => $d['jenis_kelamin'],
                    'tempat_lahir' => $d['tempat_lahir'],
                    'tanggal_lahir' => $d['tanggal_lahir'],
                    'nama_ortu' => $d['nama_ortu'],
                    'kelas_id' => $kelasPerTingkat[$d['tingkat']]->id,
                    'status' => 'Aktif',
                ]
            );
        }
    }
}
